# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[2.0,)"
# A URL to query for updates
#updateJSONURL="http://myurl.me/"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues"

[[mods]]
    modId="flintmod"
    version="9.0.0"
    displayName="Flint Instead of Wood"
    # multi line!
    description='''
		Simple replacement of wooden tools with flint counterparts. 
		It makes more sense!
    '''
    [[dependencies.flintmod]]
        modId="forge"
        mandatory=true
        versionRange="[25.0.76,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.flintmod]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.13.2]"
        ordering="NONE"
        side="BOTH"